---
# tasks file for ansible-dockerized-elk

- name: "Find out what's in the vagrant directory"
  command: ls /vagrant
  register: vagrantls

- name: "Show me what's in the vagrant directory"
  debug: msg={{ vagrantls.stdout }}

- name: "Build kibana container"
  docker_image: path="/vagrant/ansible-dockerized-elk/files/kibana" name="localkibana" state=build
  # command: docker build ../files/kibana/Dockerfile

- name: "Launch elasticsearch container"
  docker:
    name: elasticsearch
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
    - "9200:9200"
    - "9300:9300"

- name: "Launch logstash container"
  docker:
    name: logstash
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
    - /vagrant/ansible-dockerized-elk/files/logstash/config:/etc/logstash/conf.d
    ports:
    - "5000:5000"
    links:
    - elasticsearch

- name: "Launch kibana container"
  docker: 
    name: kibana
    image: localkibana
    volumes:
    - /vagrant/ansible-dockerized-elk/files/kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
    - "5601:5601"
    links:
    - elasticsearch

